/**
 * Portugal Districts and Municipalities Data
 * Used for location selection in forms and wizards
 * Data source: Official Portuguese administrative divisions
 */

export interface Municipality {
  value: string;
  label: string;
}

export interface District {
  value: string;
  label: string;
  municipalities: Municipality[];
}

/**
 * Complete list of Portuguese districts with their municipalities
 */
export const PORTUGAL_DISTRICTS: District[] = [
  {
    value: 'aveiro',
    label: 'Aveiro',
    municipalities: [
      { value: 'agueda', label: 'Águeda' },
      { value: 'albergaria-a-velha', label: 'Albergaria-a-Velha' },
      { value: 'anadia', label: 'Anadia' },
      { value: 'arouca', label: 'Arouca' },
      { value: 'aveiro', label: 'Aveiro' },
      { value: 'castelo-de-paiva', label: 'Castelo de Paiva' },
      { value: 'espinho', label: 'Espinho' },
      { value: 'estarreja', label: 'Estarreja' },
      { value: 'ilhavo', label: 'Ílhavo' },
      { value: 'mealhada', label: 'Mealhada' },
      { value: 'murtosa', label: 'Murtosa' },
      { value: 'oliveira-de-azemeis', label: 'Oliveira de Azeméis' },
      { value: 'oliveira-do-bairro', label: 'Oliveira do Bairro' },
      { value: 'ovar', label: 'Ovar' },
      { value: 'santa-maria-da-feira', label: 'Santa Maria da Feira' },
      { value: 'sao-joao-da-madeira', label: 'São João da Madeira' },
      { value: 'sever-do-vouga', label: 'Sever do Vouga' },
      { value: 'vagos', label: 'Vagos' },
      { value: 'vale-de-cambra', label: 'Vale de Cambra' },
    ],
  },
  {
    value: 'beja',
    label: 'Beja',
    municipalities: [
      { value: 'aljustrel', label: 'Aljustrel' },
      { value: 'almodovar', label: 'Almodôvar' },
      { value: 'alvito', label: 'Alvito' },
      { value: 'barrancos', label: 'Barrancos' },
      { value: 'beja', label: 'Beja' },
      { value: 'castro-verde', label: 'Castro Verde' },
      { value: 'cuba', label: 'Cuba' },
      { value: 'ferreira-do-alentejo', label: 'Ferreira do Alentejo' },
      { value: 'mertola', label: 'Mértola' },
      { value: 'moura', label: 'Moura' },
      { value: 'odemira', label: 'Odemira' },
      { value: 'ourique', label: 'Ourique' },
      { value: 'serpa', label: 'Serpa' },
      { value: 'vidigueira', label: 'Vidigueira' },
    ],
  },
  {
    value: 'braga',
    label: 'Braga',
    municipalities: [
      { value: 'amares', label: 'Amares' },
      { value: 'barcelos', label: 'Barcelos' },
      { value: 'braga', label: 'Braga' },
      { value: 'cabeceiras-de-basto', label: 'Cabeceiras de Basto' },
      { value: 'celorico-de-basto', label: 'Celorico de Basto' },
      { value: 'esposende', label: 'Esposende' },
      { value: 'fafe', label: 'Fafe' },
      { value: 'guimaraes', label: 'Guimarães' },
      { value: 'povoa-de-lanhoso', label: 'Póvoa de Lanhoso' },
      { value: 'terras-de-bouro', label: 'Terras de Bouro' },
      { value: 'vieira-do-minho', label: 'Vieira do Minho' },
      { value: 'vila-nova-de-famalicao', label: 'Vila Nova de Famalicão' },
      { value: 'vila-verde', label: 'Vila Verde' },
      { value: 'vizela', label: 'Vizela' },
    ],
  },
  {
    value: 'braganca',
    label: 'Bragança',
    municipalities: [
      { value: 'alfandega-da-fe', label: 'Alfândega da Fé' },
      { value: 'braganca', label: 'Bragança' },
      { value: 'carrazeda-de-ansiaes', label: 'Carrazeda de Ansiães' },
      { value: 'freixo-de-espada-a-cinta', label: 'Freixo de Espada à Cinta' },
      { value: 'macedo-de-cavaleiros', label: 'Macedo de Cavaleiros' },
      { value: 'miranda-do-douro', label: 'Miranda do Douro' },
      { value: 'mirandela', label: 'Mirandela' },
      { value: 'mogadouro', label: 'Mogadouro' },
      { value: 'torre-de-moncorvo', label: 'Torre de Moncorvo' },
      { value: 'vila-flor', label: 'Vila Flor' },
      { value: 'vimioso', label: 'Vimioso' },
      { value: 'vinhais', label: 'Vinhais' },
    ],
  },
  {
    value: 'castelo-branco',
    label: 'Castelo Branco',
    municipalities: [
      { value: 'belmonte', label: 'Belmonte' },
      { value: 'castelo-branco', label: 'Castelo Branco' },
      { value: 'covilha', label: 'Covilhã' },
      { value: 'fundao', label: 'Fundão' },
      { value: 'idanha-a-nova', label: 'Idanha-a-Nova' },
      { value: 'oleiros', label: 'Oleiros' },
      { value: 'penamacor', label: 'Penamacor' },
      { value: 'proenca-a-nova', label: 'Proença-a-Nova' },
      { value: 'serta', label: 'Sertã' },
      { value: 'vila-de-rei', label: 'Vila de Rei' },
      { value: 'vila-velha-de-rodao', label: 'Vila Velha de Ródão' },
    ],
  },
  {
    value: 'coimbra',
    label: 'Coimbra',
    municipalities: [
      { value: 'arganil', label: 'Arganil' },
      { value: 'cantanhede', label: 'Cantanhede' },
      { value: 'coimbra', label: 'Coimbra' },
      { value: 'condeixa-a-nova', label: 'Condeixa-a-Nova' },
      { value: 'figueira-da-foz', label: 'Figueira da Foz' },
      { value: 'gois', label: 'Góis' },
      { value: 'lousa', label: 'Lousã' },
      { value: 'mira', label: 'Mira' },
      { value: 'miranda-do-corvo', label: 'Miranda do Corvo' },
      { value: 'montemor-o-velho', label: 'Montemor-o-Velho' },
      { value: 'oliveira-do-hospital', label: 'Oliveira do Hospital' },
      { value: 'pampilhosa-da-serra', label: 'Pampilhosa da Serra' },
      { value: 'penacova', label: 'Penacova' },
      { value: 'penela', label: 'Penela' },
      { value: 'soure', label: 'Soure' },
      { value: 'tabua', label: 'Tábua' },
      { value: 'vila-nova-de-poiares', label: 'Vila Nova de Poiares' },
    ],
  },
  {
    value: 'evora',
    label: 'Évora',
    municipalities: [
      { value: 'alandroal', label: 'Alandroal' },
      { value: 'arraiolos', label: 'Arraiolos' },
      { value: 'borba', label: 'Borba' },
      { value: 'estremoz', label: 'Estremoz' },
      { value: 'evora', label: 'Évora' },
      { value: 'montemor-o-novo', label: 'Montemor-o-Novo' },
      { value: 'mora', label: 'Mora' },
      { value: 'mourao', label: 'Mourão' },
      { value: 'portel', label: 'Portel' },
      { value: 'redondo', label: 'Redondo' },
      { value: 'reguengos-de-monsaraz', label: 'Reguengos de Monsaraz' },
      { value: 'vendas-novas', label: 'Vendas Novas' },
      { value: 'viana-do-alentejo', label: 'Viana do Alentejo' },
      { value: 'vila-vicosa', label: 'Vila Viçosa' },
    ],
  },
  {
    value: 'faro',
    label: 'Faro',
    municipalities: [
      { value: 'albufeira', label: 'Albufeira' },
      { value: 'alcoutim', label: 'Alcoutim' },
      { value: 'aljezur', label: 'Aljezur' },
      { value: 'castro-marim', label: 'Castro Marim' },
      { value: 'faro', label: 'Faro' },
      { value: 'lagoa', label: 'Lagoa' },
      { value: 'lagos', label: 'Lagos' },
      { value: 'loule', label: 'Loulé' },
      { value: 'monchique', label: 'Monchique' },
      { value: 'olhao', label: 'Olhão' },
      { value: 'portimao', label: 'Portimão' },
      { value: 'sao-bras-de-alportel', label: 'São Brás de Alportel' },
      { value: 'silves', label: 'Silves' },
      { value: 'tavira', label: 'Tavira' },
      { value: 'vila-do-bispo', label: 'Vila do Bispo' },
      { value: 'vila-real-de-santo-antonio', label: 'Vila Real de Santo António' },
    ],
  },
  {
    value: 'guarda',
    label: 'Guarda',
    municipalities: [
      { value: 'aguiar-da-beira', label: 'Aguiar da Beira' },
      { value: 'almeida', label: 'Almeida' },
      { value: 'celorico-da-beira', label: 'Celorico da Beira' },
      { value: 'figueira-de-castelo-rodrigo', label: 'Figueira de Castelo Rodrigo' },
      { value: 'fornos-de-algodres', label: 'Fornos de Algodres' },
      { value: 'gouveia', label: 'Gouveia' },
      { value: 'guarda', label: 'Guarda' },
      { value: 'manteigas', label: 'Manteigas' },
      { value: 'meda', label: 'Mêda' },
      { value: 'pinhel', label: 'Pinhel' },
      { value: 'sabugal', label: 'Sabugal' },
      { value: 'seia', label: 'Seia' },
      { value: 'trancoso', label: 'Trancoso' },
      { value: 'vila-nova-de-foz-coa', label: 'Vila Nova de Foz Côa' },
    ],
  },
  {
    value: 'leiria',
    label: 'Leiria',
    municipalities: [
      { value: 'alcobaca', label: 'Alcobaça' },
      { value: 'alvaiazere', label: 'Alvaiázere' },
      { value: 'ansiao', label: 'Ansião' },
      { value: 'batalha', label: 'Batalha' },
      { value: 'bombarral', label: 'Bombarral' },
      { value: 'caldas-da-rainha', label: 'Caldas da Rainha' },
      { value: 'castanheira-de-pera', label: 'Castanheira de Pera' },
      { value: 'figueiro-dos-vinhos', label: 'Figueiró dos Vinhos' },
      { value: 'leiria', label: 'Leiria' },
      { value: 'marinha-grande', label: 'Marinha Grande' },
      { value: 'nazare', label: 'Nazaré' },
      { value: 'obidos', label: 'Óbidos' },
      { value: 'pedrogao-grande', label: 'Pedrógão Grande' },
      { value: 'peniche', label: 'Peniche' },
      { value: 'pombal', label: 'Pombal' },
      { value: 'porto-de-mos', label: 'Porto de Mós' },
    ],
  },
  {
    value: 'lisboa',
    label: 'Lisboa',
    municipalities: [
      { value: 'alenquer', label: 'Alenquer' },
      { value: 'arruda-dos-vinhos', label: 'Arruda dos Vinhos' },
      { value: 'azambuja', label: 'Azambuja' },
      { value: 'cadaval', label: 'Cadaval' },
      { value: 'cascais', label: 'Cascais' },
      { value: 'lisboa', label: 'Lisboa' },
      { value: 'loures', label: 'Loures' },
      { value: 'lourinha', label: 'Lourinhã' },
      { value: 'mafra', label: 'Mafra' },
      { value: 'oeiras', label: 'Oeiras' },
      { value: 'sintra', label: 'Sintra' },
      { value: 'sobral-de-monte-agraco', label: 'Sobral de Monte Agraço' },
      { value: 'torres-vedras', label: 'Torres Vedras' },
      { value: 'vila-franca-de-xira', label: 'Vila Franca de Xira' },
      { value: 'amadora', label: 'Amadora' },
      { value: 'odivelas', label: 'Odivelas' },
    ],
  },
  {
    value: 'portalegre',
    label: 'Portalegre',
    municipalities: [
      { value: 'alter-do-chao', label: 'Alter do Chão' },
      { value: 'arronches', label: 'Arronches' },
      { value: 'avis', label: 'Avis' },
      { value: 'campo-maior', label: 'Campo Maior' },
      { value: 'castelo-de-vide', label: 'Castelo de Vide' },
      { value: 'crato', label: 'Crato' },
      { value: 'elvas', label: 'Elvas' },
      { value: 'fronteira', label: 'Fronteira' },
      { value: 'gaviao', label: 'Gavião' },
      { value: 'marvao', label: 'Marvão' },
      { value: 'monforte', label: 'Monforte' },
      { value: 'nisa', label: 'Nisa' },
      { value: 'ponte-de-sor', label: 'Ponte de Sor' },
      { value: 'portalegre', label: 'Portalegre' },
      { value: 'sousel', label: 'Sousel' },
    ],
  },
  {
    value: 'porto',
    label: 'Porto',
    municipalities: [
      { value: 'amarante', label: 'Amarante' },
      { value: 'baiao', label: 'Baião' },
      { value: 'felgueiras', label: 'Felgueiras' },
      { value: 'gondomar', label: 'Gondomar' },
      { value: 'lousada', label: 'Lousada' },
      { value: 'maia', label: 'Maia' },
      { value: 'marco-de-canaveses', label: 'Marco de Canaveses' },
      { value: 'matosinhos', label: 'Matosinhos' },
      { value: 'pacos-de-ferreira', label: 'Paços de Ferreira' },
      { value: 'paredes', label: 'Paredes' },
      { value: 'penafiel', label: 'Penafiel' },
      { value: 'porto', label: 'Porto' },
      { value: 'povoa-de-varzim', label: 'Póvoa de Varzim' },
      { value: 'santo-tirso', label: 'Santo Tirso' },
      { value: 'valongo', label: 'Valongo' },
      { value: 'vila-do-conde', label: 'Vila do Conde' },
      { value: 'vila-nova-de-gaia', label: 'Vila Nova de Gaia' },
      { value: 'trofa', label: 'Trofa' },
    ],
  },
  {
    value: 'santarem',
    label: 'Santarém',
    municipalities: [
      { value: 'abrantes', label: 'Abrantes' },
      { value: 'alcanena', label: 'Alcanena' },
      { value: 'almeirim', label: 'Almeirim' },
      { value: 'alpiarça', label: 'Alpiarça' },
      { value: 'benavente', label: 'Benavente' },
      { value: 'cartaxo', label: 'Cartaxo' },
      { value: 'chamusca', label: 'Chamusca' },
      { value: 'constancia', label: 'Constância' },
      { value: 'coruche', label: 'Coruche' },
      { value: 'entroncamento', label: 'Entroncamento' },
      { value: 'ferreira-do-zezere', label: 'Ferreira do Zêzere' },
      { value: 'golegã', label: 'Golegã' },
      { value: 'macao', label: 'Mação' },
      { value: 'rio-maior', label: 'Rio Maior' },
      { value: 'salvaterra-de-magos', label: 'Salvaterra de Magos' },
      { value: 'santarem', label: 'Santarém' },
      { value: 'sardoal', label: 'Sardoal' },
      { value: 'tomar', label: 'Tomar' },
      { value: 'torres-novas', label: 'Torres Novas' },
      { value: 'vila-nova-da-barquinha', label: 'Vila Nova da Barquinha' },
      { value: 'ourem', label: 'Ourém' },
    ],
  },
  {
    value: 'setubal',
    label: 'Setúbal',
    municipalities: [
      { value: 'alcacer-do-sal', label: 'Alcácer do Sal' },
      { value: 'alcochete', label: 'Alcochete' },
      { value: 'almada', label: 'Almada' },
      { value: 'barreiro', label: 'Barreiro' },
      { value: 'grandola', label: 'Grândola' },
      { value: 'moita', label: 'Moita' },
      { value: 'montijo', label: 'Montijo' },
      { value: 'palmela', label: 'Palmela' },
      { value: 'santiago-do-cacem', label: 'Santiago do Cacém' },
      { value: 'seixal', label: 'Seixal' },
      { value: 'sesimbra', label: 'Sesimbra' },
      { value: 'setubal', label: 'Setúbal' },
      { value: 'sines', label: 'Sines' },
    ],
  },
  {
    value: 'viana-do-castelo',
    label: 'Viana do Castelo',
    municipalities: [
      { value: 'arcos-de-valdevez', label: 'Arcos de Valdevez' },
      { value: 'caminha', label: 'Caminha' },
      { value: 'melgaco', label: 'Melgaço' },
      { value: 'moncao', label: 'Monção' },
      { value: 'paredes-de-coura', label: 'Paredes de Coura' },
      { value: 'ponte-da-barca', label: 'Ponte da Barca' },
      { value: 'ponte-de-lima', label: 'Ponte de Lima' },
      { value: 'valenca', label: 'Valença' },
      { value: 'viana-do-castelo', label: 'Viana do Castelo' },
      { value: 'vila-nova-de-cerveira', label: 'Vila Nova de Cerveira' },
    ],
  },
  {
    value: 'vila-real',
    label: 'Vila Real',
    municipalities: [
      { value: 'alijo', label: 'Alijó' },
      { value: 'boticas', label: 'Boticas' },
      { value: 'chaves', label: 'Chaves' },
      { value: 'mesao-frio', label: 'Mesão Frio' },
      { value: 'mondim-de-basto', label: 'Mondim de Basto' },
      { value: 'montalegre', label: 'Montalegre' },
      { value: 'murca', label: 'Murça' },
      { value: 'peso-da-regua', label: 'Peso da Régua' },
      { value: 'ribeira-de-pena', label: 'Ribeira de Pena' },
      { value: 'sabrosa', label: 'Sabrosa' },
      { value: 'santa-marta-de-penaguiao', label: 'Santa Marta de Penaguião' },
      { value: 'valpacos', label: 'Valpaços' },
      { value: 'vila-pouca-de-aguiar', label: 'Vila Pouca de Aguiar' },
      { value: 'vila-real', label: 'Vila Real' },
    ],
  },
  {
    value: 'viseu',
    label: 'Viseu',
    municipalities: [
      { value: 'armamar', label: 'Armamar' },
      { value: 'carregal-do-sal', label: 'Carregal do Sal' },
      { value: 'castro-daire', label: 'Castro Daire' },
      { value: 'cinfaes', label: 'Cinfães' },
      { value: 'lamego', label: 'Lamego' },
      { value: 'mangualde', label: 'Mangualde' },
      { value: 'moimenta-da-beira', label: 'Moimenta da Beira' },
      { value: 'mortagua', label: 'Mortágua' },
      { value: 'nelas', label: 'Nelas' },
      { value: 'oliveira-de-frades', label: 'Oliveira de Frades' },
      { value: 'penalva-do-castelo', label: 'Penalva do Castelo' },
      { value: 'penedono', label: 'Penedono' },
      { value: 'resende', label: 'Resende' },
      { value: 'santa-comba-dao', label: 'Santa Comba Dão' },
      { value: 'sao-joao-da-pesqueira', label: 'São João da Pesqueira' },
      { value: 'sao-pedro-do-sul', label: 'São Pedro do Sul' },
      { value: 'satao', label: 'Sátão' },
      { value: 'sernancelhe', label: 'Sernancelhe' },
      { value: 'tabuaco', label: 'Tabuaço' },
      { value: 'tarouca', label: 'Tarouca' },
      { value: 'tondela', label: 'Tondela' },
      { value: 'vila-nova-de-paiva', label: 'Vila Nova de Paiva' },
      { value: 'viseu', label: 'Viseu' },
      { value: 'vouzela', label: 'Vouzela' },
    ],
  },
];

/**
 * Get municipalities for a specific district
 */
export function getMunicipalitiesByDistrict(districtValue: string): Municipality[] {
  const district = PORTUGAL_DISTRICTS.find(d => d.value === districtValue);
  return district?.municipalities || [];
}

/**
 * Get district label by value
 */
export function getDistrictLabel(districtValue: string): string {
  const district = PORTUGAL_DISTRICTS.find(d => d.value === districtValue);
  return district?.label || districtValue;
}

/**
 * Get municipality label by value
 */
export function getMunicipalityLabel(districtValue: string, municipalityValue: string): string {
  const municipalities = getMunicipalitiesByDistrict(districtValue);
  const municipality = municipalities.find(m => m.value === municipalityValue);
  return municipality?.label || municipalityValue;
}
